---
- name: Install Caddy dependencies
  become: true
  ansible.builtin.dnf5:
    name:
      - nomad
      - nomad-driver-podman
      - nomad-autoscaler
    state: present

- name: Create Gitea directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nomad_server.nomad.user.name }}"
    group: "{{ nomad_server.nomad.user.group }}"
    mode: "0755"
  loop:
    - "{{ gitea_config.data_dir }}"
    - "{{ gitea_config.data_dir }}/data"
    - "{{ gitea_config.data_dir }}/config"
