---
- name: Install Nomad
  become: true
  dnf5:
    name:
      - nomad
      - nomad-driver-podman
      - nomad-autoscaler
      - consul-cni
    state: present

- name: Get {{ nomad.user.name }} UID
  command: id -u {{ nomad.user.name }}
  register: nomad_uid
  changed_when: false

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nomad.user.name }}"
    group: "{{ nomad.user.name }}"
    mode: "0755"
  loop:
    - /opt/nomad
    - /opt/nomad/data
    - /etc/nomad.d
    - /etc/nomad.d/certs
    - /opt/cni/bin

- name: Nomad config
  template:
    src: ../templates/nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: "{{ nomad.user.name }}"
    group: "{{ nomad.user.name }}"
    mode: 0644

- name: Request Nomad certificate from Vault
  community.hashi_vault.vault_write:
    url: "http://{{ ansible_default_ipv4.address }}:8200"
    token: "{{ vault_root_token }}"
    path: pki/issue/nomad
    data:
      common_name: "{{ inventory_hostname }}"
  register: nomad_cert

- name: Write Nomad certificate
  copy:
    dest: "{{ nomad.vault.cert_file }}"
    content: "{{ nomad_cert.data.data.certificate }}"
    owner: "{{ nomad.user.name }}"
    group: "{{ nomad.user.name }}"
    mode: "0644"

- name: Write CA certificate
  copy:
    dest: "{{ nomad.vault.ca_file }}"
    content: "{{ nomad_cert.data.data.issuing_ca }}"
    owner: "{{ nomad.user.name }}"
    group: "{{ nomad.user.name }}"
    mode: "0644"

- name: Write Nomad private key
  copy:
    dest: "{{ nomad.vault.key_file }}"
    content: "{{ nomad_cert.data.data.private_key }}"
    owner: "{{ nomad.user.name }}"
    group: "{{ nomad.user.name }}"
    mode: "0640"

- name: Enable and start Nomad service
  systemd:
    name: nomad.service
    enabled: true
    state: started
    daemon_reload: yes
    no_block: false

- name: Wait for Nomad API
  uri:
    url: http://127.0.0.1:4646/v1/status/leader
    validate_certs: false
  register: nomad_api
  retries: 20
  delay: 3
  until: nomad_api.status == 200
  changed_when: false

- name: Check Nomad service status
  command: nomad status
  environment:
    NOMAD_ADDR: http://127.0.0.1:4646
  register: nomad_status

- debug:
    msg: >
      Nomad service status: {{ nomad_status.stdout }}
      Nomad API status: {{ nomad_api.status }}
      Nomad API response: {{ nomad_api.content }}
