---
- name: Check linger status for "{{ podman_rootless.user }}"
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ podman_rootless.user }}"
  register: user_linger_status

- name: Enable linger for "{{ podman_rootless.user }}"
  ansible.builtin.command: loginctl enable-linger {{ podman_rootless.user }}
  become: true
  changed_when: true
  when: not user_linger_status.stat.exists

- name: Enable Podman user socket
  become: true
  become_user: "{{ podman_rootless.user }}"
  ansible.builtin.systemd:
    name: podman.socket
    scope: user
    enabled: true
    state: started
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_rootless.uid }}"

- name: Check Podman socket
  ansible.builtin.stat:
    path: "/run/user/{{ podman_rootless.uid }}/podman/podman.sock"
  register: podman_socket

- name: Verify Podman socket exists
  ansible.builtin.assert:
    that:
      - podman_socket.stat.exists
      - podman_socket.stat.issock
    fail_msg: "Rootless Podman socket was not created"
