---
podman:
  user:
    name: nomad
    comment: Nomad User
    group: podman
    append: true
    create_home: true
    system: true
    shell: /bin/bash
    subid_start: 296608
    subid_range: 65536
