---
- name: Install Podman
  become: true
  dnf5:
    name: podman
    state: present

- name: Get {{podman.user.name}} UID
  command: id -u {{podman.user.name}}
  register: podman_uid
  changed_when: false

- name: Enable Podman socket for {{podman.user.name}}
  systemd:
    name: podman.socket
    scope: user
    enabled: yes
    state: started
  become: true
  become_user: "{{ podman.user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_uid.stdout }}"
  register: podman_output

- name: Show Podman info
  become: true
  become_user: "{{podman.user.name}}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{podman_uid.stdout}}"
  command: podman info
  register: podman_output

- name: Show Podman output
  debug:
    var: podman_output.stdout

- name: Run test container
  become: true
  become_user: "{{podman.user.name}}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{podman_uid.stdout}}"
  command: podman run --name podman_test --rm docker.io/library/alpine echo hello
  register: podman_output

- name: Show Podman output
  debug:
    var: podman_output.stdout
