---
- name: Install Vault
  become: true
  dnf5:
    name: vault
    state: present

- name: Get {{ vault.user.name }} UID
  command: id -u {{ vault.user.name }}
  register: vault_uid
  changed_when: false

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault.user.name }}"
    group: "{{ vault.user.group }}"
    mode: "0755"
  loop:
    - /etc/vault.d
    - /opt/vault/data
    - /etc/vault.d/tls

- name: Generate bootstrap Vault TLS certificate
  command: >
    openssl req -x509 -nodes -days 3650
    -newkey rsa:4096
    -keyout /etc/vault.d/tls/vault.key
    -out /etc/vault.d/tls/vault.crt
    -subj "/CN={{ ansible_hostname }}"
  args:
    creates: /etc/vault.d/tls/vault.crt

- name: Set vault.key file permissions
  file:
    path: "/etc/vault.d/tls/vault.key"
    owner: "{{ vault.user.name }}"
    group: "{{ vault.user.group }}"
    mode: "0600"

- name: Set vault.crt file permissions
  file:
    path: "/etc/vault.d/tls/vault.crt"
    owner: "{{ vault.user.name }}"
    group: "{{ vault.user.group }}"
    mode: "0640"

- name: Vault config
  template:
    src: ../templates/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl

- name: Enable and start Vault service
  systemd:
    name: vault.service
    enabled: true
    state: started
    daemon_reload: yes
    no_block: false

- name: Wait for Vault API
  uri:
    url: "{{ nomad_server.vault.addr }}/v1/sys/health"
    method: GET
  register: vault_health
  retries: 20
  delay: 3
  until: vault_health.status != -1
  failed_when: false
  changed_when: false

- name: Check Vault status
  command: vault status -format=json
  environment:
    VAULT_ADDR: "{{ nomad_server.vault.addr }}"
  register: vault_status
  changed_when: false
  failed_when: false

- debug:
    msg: >
      Vault Status:
      {{ vault_status.stdout }}

- name: Check Vault service registration in Consul
  shell: consul catalog services
  register: consul_services
  changed_when: false
  failed_when: "'vault' not in consul_services.stdout"

- debug:
    msg: "Vault registered services: {{ consul_services.stdout }}"
