---
- name: Run CoreDNS Nomad job
  ansible.builtin.command: nomad job run {{ coredns_config.nomad_job_path }}
  environment:
    NOMAD_ADDR: "https://127.0.0.1:4646"
    NOMAD_SKIP_VERIFY: true
    NOMAD_TOKEN: "{{ nomad_management_token }}"
  changed_when: true
  notify: Wait for CoreDNS

- name: Wait for CoreDNS
  ansible.builtin.command: "dig @127.0.0.1 home.arpa"
  register: dns_check
  retries: 10
  delay: 3
  until: dns_check.rc == 0

- name: Point resolved to CoreDNS
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/coredns.conf
    mode: "0644"
    content: |
      [Resolve]
      DNS=127.0.0.1
  notify: Restart systemd-resolved

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
