---
all:
  vars:
    ansible_become_method: sudo

nomad_servers:
  hosts:
    nomad_server1:
      ansible_host: home-server-1.lan
  vars:
    nomad_server:
      consul:
        nomad_token: "{{lookup('env', 'CONSUL_NOMAD_TOKEN')}}"
        dns_addr: 127.0.0.1:8600
      vault:
        addr: "https://127.0.0.1:8200"
        hostname: "vault.service.consul"
        root_token: "{{ lookup('env', 'VAULT_ROOT_TOKEN')}}"
        unseal_keys: "{{ lookup('env', 'VAULT_UNSEAL_KEYS') | split(',') }}"
        nomad:
          role: "nomad-cluster"
          management-token: "{{lookup('env', 'NOMAD_TOKEN')}}"
          token_file: "/etc/nomad.d/vault_nomad_token"
          key_file: "/etc/nomad.d/certs/nomad-key.pem"
      nomad:
        addr: "https://127.0.0.1:4646"
        acl:
          bootstrap_token_file: "/etc/nomad.d/nomad-management-token.txt"
        user:
          name: nomad
          group: nomad
        vault:
          ca_file: "/etc/nomad.d/certs/ca.pem"
          cert_file: "/etc/nomad.d/certs/nomad.pem"
          key_file: "/etc/nomad.d/certs/nomad-key.pem"
