---
gitea_config:
  nomad_job_path: /etc/nomad.d/jobs/gitea.nomad
  datacenters:
    - homelab
  image: docker.gitea.com/gitea:1.26.2-rootless
  nomad_namespace: development
  data_dir: /opt/gitea
  port: 3000
  ssh_port: 2222
  sqlite_timeout: 20000
