---
- name: Create postgres storage directory
  ansible.builtin.file:
    path: "{{ postgres_config.data_dir }}"
    state: directory
    owner: "{{ nomad_server.nomad.user.name }}"
    group: "{{ nomad_server.nomad.user.group }}"
    mode: "0750"

- name: Render PostgreSQL Nomad job
  ansible.builtin.template:
    src: postgres.nomad.j2
    dest: "{{ postgres_config.nomad_job_path }}"
    mode: "0644"

- name: Read Nomad bootstrap token from remote server
  ansible.builtin.slurp:
    src: /etc/nomad.d/nomad-management-token.txt
  register: nomad_token_slurp
  no_log: true

- name: Set Nomad token fact
  ansible.builtin.set_fact:
    nomad_management_token: "{{ (nomad_token_slurp.content | b64decode | from_json).SecretID }}"
  no_log: true

- name: Ensure {{ postgres_config.nomad_namespace }} namespace exists
  environment:
    NOMAD_ADDR: "{{ nomad_server.nomad.addr }}"
    NOMAD_SKIP_VERIFY: "true"
    NOMAD_CACERT: "{{ nomad_server.nomad.vault.ca_file }}"
    NOMAD_CLIENT_CERT: "{{ nomad_server.nomad.vault.cert_file }}"
    NOMAD_CLIENT_KEY: "{{ nomad_server.nomad.vault.key_file }}"
    NOMAD_TOKEN: "{{ nomad_management_token }}"
  ansible.builtin.command:
    cmd: >
      nomad namespace apply {{ caddy_config.nomad_namespace }}
  register: nomad_namespace_apply
  changed_when: >
    "Successfully applied namespace" in nomad_namespace_apply.stdout

- name: Register PostgreSQL job with Nomad
  ansible.builtin.command:
    cmd: nomad job run /etc/nomad.d/jobs/postgres.nomad.hcl
  register: nomad_postgres_run
  changed_when: "'Job registered' in nomad_postgres_run.stdout or 'Evaluation' in nomad_postgres_run.stdout"

- name: Wait for PostgreSQL service to be healthy in Consul
  ansible.builtin.uri:
    url: "http://127.0.0.1:8500/v1/health/service/postgres?passing=true"
    method: GET
  register: consul_postgres_health
  retries: 30
  delay: 5
  until: consul_postgres_health.json | length > 0
