---
- name: Install dependencies
  dnf5:
    name:
      - python3-hvac
    state: present

- name: Enable PKI secrets engine
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: sys/mounts/pki
    data:
      type: pki
  ignore_errors: true

- name: Configure PKI TTL
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: sys/mounts/pki/tune
    data:
      max_lease_ttl: 87600h

- name: Generate root CA
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: pki/root/generate/internal
    data:
      common_name: "homelab-ca"
      ttl: 87600h

- name: Create Nomad PKI role
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: pki/roles/nomad
    data:
      allow_any_name: true
      enforce_hostnames: false
      max_ttl: "72h"
