---
- name: Install dependencies
  dnf5:
    name:
      - python3-hvac
    state: present

- name: Check current Vault mounts
  community.hashi_vault.vault_read:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: sys/mounts
    validate_certs: true
  register: vault_mounts

- name: Enable PKI secrets engine
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: sys/mounts/pki
    validate_certs: true
    data:
      type: pki
      config:
        max_lease_ttl: 87600h
  when: "'pki/' not in vault_mounts.data.data"

- name: Configure PKI TTL
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: sys/mounts/pki/tune
    validate_certs: true
    data:
      max_lease_ttl: 87600h

- name: Generate root CA
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: pki/root/generate/internal
    validate_certs: true
    data:
      common_name: "homelab-ca"
      ttl: 87600h
  no_log: true

- name: Create Nomad PKI role
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: pki/roles/nomad
    validate_certs: true
    data:
      allow_any_name: true
      enforce_hostnames: false
      max_ttl: "72h"
