---
- name: Setup Fedora Server with Nomad
  hosts: "{{ target_hosts | default('nomad_servers') }}"
  become: true
  roles:
    - automatic_updates
    - hashicorp_repo
    - setup_podman
    - setup_consul
    - setup_vault
    - setup_nomad
