---
- name: Setup Fedora Server with Nomad
  hosts: "{{ target_hosts | default('nomad_servers') }}"
  become: true
  roles:
    - automatic_updates
    - hashicorp_repo
    - podman
    - consul
    - vault
    - vault_pki
    - nomad
