---
- name: Setup Fedora Server with Nomad
  hosts: "{{ target_hosts | default('nomad_servers') }}"
  become: true
  vars:
    nomad_user: nomad
  roles:
    - automatic_updates
    - hashicorp_repo
    - setup_nomad_user
#    - setup_podman
