---
- name: Ensure group "{{user_group}}" exists
  ansible.builtin.group:
    name: "{{user_group}}"
    state: present

- name: Create a user "{{user_name}}"
  user:
    name: "{{user_name}}"
    comment: Setup user {{user_name}}
    groups: "{{user_group}}"
    append: "{{user_append}}"
    create_home: "{{user_create_home}}"
    system: "{{user_system}}"
    shell: "{{user_shell}}"

- name: Configure subuid for "{{user_name}}"
  lineinfile:
    path: /etc/subuid
    line: "{{user_name}}:{{user_subid_start}}:{{user_subid_range}}"
    create: true
  become: true

- name: Check if linger is enabled
  stat:
    path: /var/lib/systemd/linger/{{podman}}
  register: linger_status

- name: Enable linger for "{{user_name}}"
  ansible.builtin.command: loginctl enable-linger {{user_name}}
  become: true
  when: not linger_status.stat.exists

- name: Get "{{user_name}}" UID
  command: id -u {{user_name}}
  register: user_name_uid
  changed_when: false

- name: Show "{{user_name}}" uid
  debug:
    msg: "User {{user_name}} UID is {{user_name_uid.stdout}}"

- name: Set "{{user_name}}" UID
  set_fact:
    user_name_uid: "{{ user_name_uid.stdout }}"
