---
caddy_config:
  job_name: caddy
  datacenters:
    - homelab
  image: docker.io/library/caddy:2.10
  nomad_namespace: ingress
  data_dir: /opt/caddy
  email: rlperez@kablamo.me
  upstreams:
    - host: vault.home.arpa
      upstream: "127.0.0.1:8200"
    - host: nomad.home.arpa
      upstream: "127.0.0.1:4646"
    - host: consul.home.arpa
      upstream: "127.0.0.1:8500"
  http_port: 80
  https_port: 443
  admin_port: 2019
  constraints: []
  job_type: service
