---
caddy_config:
  nomad_job_path: /etc/nomad.d/jobs/caddy.nomad
  datacenters:
    - homelab
  image: docker.io/library/caddy:2-alpine
  nomad_namespace: ingress
  data_dir: /opt/caddy
  upstreams:
    - host: vault.home.arpa
      upstream: "vault.service.consul:8200"
      tls_upstream: true
    - host: nomad.home.arpa
      upstream: "nomad.service.consul:4646"
      tls_upstream: true
    - host: consul.home.arpa
      upstream: "consul.service.consul:8500"
      tls_upstream: false
    - host: git.home.arpa
      upstream: "gitea.service.consul:3000"
      tls_upstream: true
  http_port: 80
  https_port: 443
  admin_port: 2019
  constraints: []
  job_type: system
