---
- name: Install Nomad
  become: true
  ansible.builtin.dnf5:
    name:
      - nomad
      - nomad-driver-podman
      - nomad-autoscaler
      - consul-cni
      - containernetworking-plugins
    state: present

- name: Get UID for {{ nomad_user.name }}
  ansible.builtin.command: id -u {{ nomad_user.name }}
  register: nomad_uid
  changed_when: false

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nomad_user.name }}"
    group: "{{ nomad_user.name }}"
    mode: "0755"
  loop:
    - /opt/nomad
    - /opt/nomad/data
    - /etc/nomad.d
    - /etc/nomad.d/certs
    - /opt/cni/bin

- name: Check if Nomad certificate exists
  ansible.builtin.stat:
    path: "{{ nomad_vault.cert_file }}"
  register: nomad_cert_file

- name: Check if Nomad certificates exist
  ansible.builtin.stat:
    path: "{{ nomad_vault.ca_file }}"
  register: nomad_ca_file

- name: Request Nomad certificate from Vault
  community.hashi_vault.vault_write:
    url: "{{ nomad_server.vault.addr }}"
    token: "{{ nomad_server.vault.root_token }}"
    path: pki/issue/nomad
    data:
      common_name: "{{ ansible_hostname }}"
      alt_names: "localhost,{{ ansible_hostname }}.node.consul,nomad.service.consul"
      ip_sans: "127.0.0.1,{{ ansible_default_ipv4.address }}"
  register: nomad_cert
  no_log: true
  when: not nomad_ca_file.stat.exists

- name: Write Nomad certificate
  ansible.builtin.copy:
    dest: "{{ nomad_vault.cert_file }}"
    content: "{{ nomad_cert.data.data.certificate }}"
    owner: "{{ nomad_user.name }}"
    group: "{{ nomad_user.name }}"
    mode: "0644"
  when: not nomad_cert_file.stat.exists

- name: Write CA certificate
  ansible.builtin.copy:
    dest: "{{ nomad_vault.ca_file }}"
    content: "{{ nomad_cert.data.data.issuing_ca }}"
    owner: "{{ nomad_user.name }}"
    group: "{{ nomad_user.name }}"
    mode: "0644"
  when: not nomad_cert_file.stat.exists

- name: Write Nomad private key
  ansible.builtin.copy:
    dest: "{{ nomad_vault.key_file }}"
    content: "{{ nomad_cert.data.data.private_key }}"
    owner: "{{ nomad_user.name }}"
    group: "{{ nomad_user.name }}"
    mode: "0640"
  when: not nomad_cert_file.stat.exists

- name: Ensure Vault is reachable
  ansible.builtin.uri:
    url: "{{ nomad_server.vault.addr }}/v1/sys/health"
    method: GET
  register: nomad_vault_health
  retries: 10
  delay: 5
  until: nomad_vault_health.status == 200

- name: Check if Nomad policy exists
  ansible.builtin.uri:
    url: "{{ nomad_server.vault.addr }}/v1/sys/policies/acl/nomad-cluster"
    method: GET
    headers:
      X-Vault-Token: "{{ nomad_server.vault.root_token }}"
    validate_certs: false
  register: nomad_policy_lookup
  changed_when: false
  failed_when: false

- name: Create Nomad policy in Vault
  ansible.builtin.command: |
    vault policy write nomad-cluster - <<'EOF'
    path "secret/data/nomad/*" {
      capabilities = ["read", "list"]
    }

    path "pki_int/issue/nomad" {
      capabilities = ["create", "update"]
    }
    EOF
  environment:
    VAULT_ADDR: "{{ nomad_server.vault.addr }}"
    VAULT_TOKEN: "{{ nomad_server.vault.root_token }}"
  register: nomad_policy
  changed_when: false
  when: nomad_policy_lookup.status != 200

- name: Check if Nomad Vault token file exists
  ansible.builtin.stat:
    path: /etc/nomad.d/vault-token.txt
  register: nomad_vault_token_file

- name: Create Nomad token in Vault
  ansible.builtin.command: vault token create -policy="nomad-cluster" -format=json
  environment:
    VAULT_ADDR: "{{ nomad_server.vault.addr }}"
    VAULT_TOKEN: "{{ nomad_server.vault.root_token }}"
  register: nomad_vault_token_json
  changed_when: true
  when: not nomad_vault_token_file.stat.exists
  no_log: true

- name: Save Nomad Vault token to file
  ansible.builtin.copy:
    content: "{{ (nomad_vault_token_json.stdout | from_json).auth.client_token }}"
    dest: /etc/nomad.d/vault-token.txt
    owner: "{{ nomad_user.name }}"
    group: "{{ nomad_user.name }}"
    mode: "0600"
  when:
    - not nomad_vault_token_file.stat.exists
    - nomad_acl_bootstrap.rc | default(1) == 0
  no_log: true

- name: Read Nomad Vault token from file
  ansible.builtin.slurp:
    src: /etc/nomad.d/vault-token.txt
  register: nomad_vault_token_b64
  no_log: true

- name: Set nomad_vault_token fact
  ansible.builtin.set_fact:
    nomad_vault_token: "{{ nomad_vault_token_b64.content | b64decode }}"
  no_log: true

- name: Nomad config
  ansible.builtin.template:
    src: "{{ role_path }}/templates/nomad.hcl.j2"
    dest: /etc/nomad.d/nomad.hcl
    owner: "{{ nomad_user.name }}"
    group: "{{ nomad_user.name }}"
    mode: "0644"

- name: Enable and start system Podman socket (Required for Nomad driver)
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true
    state: started

- name: Enable and start Nomad service
  ansible.builtin.systemd:
    name: nomad.service
    enabled: true
    state: restarted
    daemon_reload: true
    no_block: false

- name: Wait for Nomad API (Using HTTPS)
  ansible.builtin.uri:
    url: "{{ nomad_server.nomad.addr }}/v1/status/leader"
    validate_certs: false
  register: nomad_api
  retries: 20
  delay: 3
  until: nomad_api.status == 200
  changed_when: false

- name: Check if Nomad bootstrap token exists
  ansible.builtin.stat:
    path: "{{ nomad_server.nomad.acl.bootstrap_token_file }}"
  register: token_file

- name: Bootstrap Nomad ACLs
  ansible.builtin.command: nomad acl bootstrap -json
  environment:
    NOMAD_ADDR: "{{ nomad_server.nomad.addr }}"
    NOMAD_CACERT: "{{ nomad_vault.ca_file }}"
  register: nomad_acl_bootstrap
  when: not token_file.stat.exists
  failed_when:
    - nomad_acl_bootstrap.rc != 0
    - "'ACL bootstrap already done' not in nomad_acl_bootstrap.stderr"
  changed_when: nomad_acl_bootstrap.rc == 0

- name: Save Nomad bootstrap token to file
  ansible.builtin.copy:
    content: "{{ nomad_acl_bootstrap.stdout }}"
    dest: "{{ nomad_server.nomad.acl.bootstrap_token_file }}"
    owner: "{{ nomad_user.name }}"
    group: "{{ nomad_user.name }}"
    mode: "0600"
  when:
    - not token_file.stat.exists
    - nomad_acl_bootstrap.rc | default(1) == 0

- name: Read current Nomad bootstrap token
  ansible.builtin.slurp:
    src: "{{ nomad_server.nomad.acl.bootstrap_token_file }}"
  register: nomad_token_file

- name: Set Nomad token fact
  ansible.builtin.set_fact:
    nomad_management_token: "{{ (nomad_token_file.content | b64decode | from_json).SecretID }}"

- name: Check Nomad service status
  ansible.builtin.command: nomad status
  environment:
    NOMAD_ADDR: "{{ nomad_server.nomad.addr }}"
    NOMAD_CACERT: "{{ nomad_vault.ca_file }}"
    NOMAD_TOKEN: "{{ nomad_management_token }}"
  register: nomad_status
  changed_when: false
  no_log: true

- name: Debug Nomad service status
  ansible.builtin.debug:
    msg: >
      Nomad service status: {{ nomad_status.stdout }}
      Nomad API status: {{ nomad_api.status }}
      Nomad Leader: {{ nomad_api.json | default('Unknown') }}
