---
- name: Install Podman
  become: true
  ansible.builtin.dnf5:
    name: podman
    state: present

- name: Get UID for {{ podman_user.name }}
  ansible.builtin.command: id -u {{ podman_user.name }}
  register: podman_uid
  changed_when: false

- name: Enable Podman socket for {{ podman_user.name }}
  ansible.builtin.systemd:
    name: podman.socket
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ podman_user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_uid.stdout }}"
  register: podman_output

- name: Show Podman info
  become: true
  become_user: "{{ podman_user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_uid.stdout }}"
  ansible.builtin.command: podman info
  changed_when: false
  register: podman_output

- name: Show Podman output
  ansible.builtin.debug:
    var: podman_output.stdout

- name: Run test container
  become: true
  become_user: "{{ podman_user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ podman_uid.stdout }}"
  ansible.builtin.command: podman run --name podman_test --rm docker.io/library/alpine echo hello
  register: podman_output
  changed_when: false

- name: Show Podman output
  ansible.builtin.debug:
    var: podman_output.stdout
