---
dependencies:
  - role: user
    vars:
      user_name: "{{ vault.user.name }}"
      user_comment: "{{ vault.user.comment }}"
      user_group: "{{ vault.user.group }}"
      user_subid_start: "{{ vault.user.subid_start }}"
