---
- name: Ensure group "{{nomad_user}}" exists
  ansible.builtin.group:
    name: "{{nomad_user}}"
    state: present

- name: Create a user "{{nomad_user}}"
  ansible.builtin.user:
    name: "{{nomad_user}}"
    comment: Nomad User to run Nomad and associated services
    group: "{{nomad_user}}"
    append: true
    create_home: true
    system: true
    shell: /usr/sbin/nologin

- name: Configure subuid for "{{nomad_user}}"
  lineinfile:
    path: /etc/subuid
    line: "{{nomad_user}}:100000:65536"
    create: true
  become: true

- name: Configure subgid for "{{nomad_user}}"
  lineinfile:
    path: /etc/subgid
    line: "{{nomad_user}}:100000:65536"
    create: true
  become: true

- name: Get "{{nomad_user}}" UID
  command: id -u {{nomad_user}}
  register: nomad_uid
  changed_when: false

- name: Show "{{nomad_user}}" uid
  debug:
    msg: "User {{nomad_user}} UID is {{nomad_uid.stdout}}"
