---
- name: Install dnf5-plugin-automatic
  become: true
  ansible.builtin.dnf5:
    name: dnf5-plugin-automatic
    state: present

- name: Copy and configure automatic.conf
  ansible.builtin.template:
    src: "{{ role_path }}/templates/automatic.conf.j2"
    dest: /etc/dnf/automatic.conf
    mode: "0644"
    owner: root
    group: root

- name: Enable and start dnf5-automatic.timer
  ansible.builtin.systemd:
    name: dnf5-automatic.timer
    enabled: true
    state: started
