---
- name: Install dnf5-plugin-automatic
  become: true
  dnf5:
    name: dnf5-plugin-automatic
    state: present

- name: Copy and configure automatic.conf
  template:
    src: ../templates/automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    mode: "0644"
    owner: root
    group: root

- name: Enable and start dnf5-automatic.timer
  systemd:
    name: dnf5-automatic.timer
    enabled: true
    state: started
